# Generated by Django 5.1.7 on 2025-07-08 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_student_email_alter_student_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='app.program'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timetable',
            name='start_time',
            field=models.TimeField(choices=[('08:30:00', '08:30 AM - 09:30 AM'), ('09:30:00', '09:30 AM - 10:30 AM'), ('10:30:00', '10:30 AM - 11:30 AM'), ('12:00:00', '12:00 PM - 01:00 PM'), ('01:00:00', '01:00 PM - 02:00 PM')]),
        ),
    ]
